use hashbrown::HashMap;
use lekhani_core::phonetic::PhoneticSuggestion;

#[test]
fn test_massive_deep_simulation_suite() {
    let mut sugg = PhoneticSuggestion::new();
    let layout_candidates = [
        std::path::Path::new("../../data/layouts/avrophonetic.json"),
        std::path::Path::new("data/layouts/avrophonetic.json"),
        std::path::Path::new("../data/layouts/avrophonetic.json"),
    ];
    for p in layout_candidates {
        if p.exists() {
            if let Ok(content) = std::fs::read_to_string(p) {
                if let Ok(json) = serde_json::from_str(&content) {
                    sugg.set_layout(&json);
                    break;
                }
            }
        }
    }
    let empty_memory = HashMap::new();

    let test_cases: &[(&str, &[&str])] = &[
        // 1. Conversational Pronouns & Greetings
        ("kemon", &["কেমন"]),
        ("acho", &["আছো"]),
        ("achen", &["আছেন"]),
        ("tumi", &["তুমি"]),
        ("apni", &["আপনি"]),
        ("amra", &["আমরা"]),
        ("tomra", &["তোমরা"]),
        ("tara", &["তারা"]),
        ("tini", &["তিনি"]),
        ("apnara", &["আপনারা"]),
        ("shobai", &["সবাই"]),
        ("shobaike", &["সবাইকে"]),
        ("amader", &["আমাদের"]),
        ("tomader", &["তোমাদের"]),
        ("tader", &["তাদের"]),
        ("apnader", &["আপনাদের"]),
        ("amake", &["আমাকে"]),
        ("tomake", &["তোমাকে"]),
        ("take", &["তাকে"]),
        ("apnake", &["আপনাকে"]),

        // 2. High Frequency Conversational Verbs (Present, Past, Future, Continuous)
        ("kori", &["করি"]),
        ("koro", &["করো"]),
        ("kore", &["করে"]),
        ("koren", &["করেন"]),
        ("korlam", &["করলাম"]),
        ("korle", &["করলে"]),
        ("korlo", &["করল"]),
        ("korlen", &["করলেন"]),
        ("korbo", &["করব"]),
        ("korbe", &["করবে"]),
        ("korben", &["করবেন"]),
        ("korcho", &["করছো"]),
        ("korche", &["করছে"]),
        ("korchen", &["করছেন"]),
        ("korchi", &["করছি"]),
        ("kortesi", &["করছি", "করতেছি"]),
        ("korteso", &["করছো", "করতেছো"]),
        ("kortese", &["করছে", "করতেছে"]),
        ("kortesen", &["করছেন", "করতেছেন"]),
        ("korchilam", &["করছিলাম"]),
        ("korchilen", &["করছিলেন"]),
        ("korchilo", &["করছিল"]),
        ("korchile", &["করছিলে"]),
        ("dekhi", &["দেখি"]),
        ("dekho", &["দেখো"]),
        ("dekhe", &["দেখে"]),
        ("dekhen", &["দেখেন"]),
        ("dekhlam", &["দেখলাম"]),
        ("dekhbo", &["দেখব"]),
        ("dekhbe", &["দেখবে"]),
        ("dekhben", &["দেখবেন"]),
        ("dekhtesi", &["দেখছি", "দেখতেছি"]),
        ("dekhtesilam", &["দেখতেছিলাম", "দেখছিলাম"]),
        ("jabo", &["যাব"]),
        ("jabe", &["যাবে"]),
        ("jaben", &["যাবেন"]),
        ("jabi", &["যাবি"]),
        ("jacci", &["যাচ্ছি"]),
        ("jacchi", &["যাচ্ছি"]),
        ("jaitasi", &["যাচ্ছি", "যাইতেছি"]),
        ("jaitesilen", &["যাইতেছিলেন", "যাচ্ছিলেন"]),
        ("gelam", &["গেলাম"]),
        ("gele", &["গেলে"]),
        ("gelo", &["গেল"]),
        ("gelen", &["গেলেন"]),
        ("gechi", &["গেছি", "গিয়েছি"]),
        ("geche", &["গেছে", "গিয়েছে"]),
        ("gechen", &["গেছেন", "গিয়েছেন"]),
        ("ashbo", &["আসব"]),
        ("ashbe", &["আসবে"]),
        ("ashben", &["আসবেন"]),
        ("ashlam", &["আসলাম"]),
        ("ashlo", &["আসল"]),
        ("ashlen", &["আসলেন"]),
        ("esho", &["এসো"]),
        ("ashun", &["আসুন"]),
        ("eshechi", &["এসেছি"]),
        ("esheche", &["এসেছে"]),
        ("eshechen", &["এসেছেন"]),
        ("khabo", &["খাব"]),
        ("khabe", &["খাবে"]),
        ("khaben", &["খাবেন"]),
        ("khacchi", &["খাচ্ছি"]),
        ("kheyechi", &["খেয়েছি"]),
        ("kheyecho", &["খেয়েছো"]),
        ("kheyeche", &["খেয়েছে"]),
        ("kheyechen", &["খেয়েছেন"]),
        ("bolbo", &["বলব"]),
        ("bolbe", &["বলবে"]),
        ("bolben", &["বলবেন"]),
        ("bolo", &["বলো"]),
        ("bolun", &["বলুন"]),
        ("bollam", &["বললাম"]),
        ("bollo", &["বলল"]),
        ("bollen", &["বললেন"]),
        ("shunbo", &["শুনব"]),
        ("shuno", &["শুনো"]),
        ("shunlam", &["শুনলাম"]),
        ("shunechi", &["শুনেছি"]),
        ("shunecho", &["শুনেছো"]),
        ("shuneche", &["শুনেছে"]),
        ("parbo", &["পারব"]),
        ("parbe", &["পারবে"]),
        ("parben", &["পারবেন"]),
        ("paro", &["পারো"]),
        ("pari", &["পারি"]),
        ("pare", &["পারে"]),
        ("paren", &["পারেন"]),
        ("parlam", &["পারলাম"]),
        ("parlo", &["পারল"]),
        ("parlen", &["পারলেন"]),
        ("cholo", &["চলো"]),
        ("choli", &["চলি"]),
        ("chole", &["চলে"]),
        ("cholen", &["চলেন"]),
        ("chollo", &["চলল"]),
        ("cholche", &["চলছে"]),
        ("choltese", &["চলছে", "চলতেছে"]),
        ("hobe", &["হবে"]),
        ("holo", &["হলো"]),
        ("hoyeche", &["হয়েছে"]),
        ("hocche", &["হচ্ছে"]),
        ("hotam", &["হতাম"]),
        ("hoto", &["হতো"]),
        ("thakbo", &["থাকব"]),
        ("thako", &["থাকো"]),
        ("thaki", &["থাকি"]),
        ("thake", &["থাকে"]),
        ("thaken", &["থাকেন"]),
        ("thaklam", &["থাকলাম"]),
        ("thaklo", &["থাকল"]),
        ("thaklen", &["থাকলেন"]),

        // 3. Daily Relations, Slang, Connectors & Emphatics
        ("bhai", &["ভাই"]),
        ("bhaiya", &["ভাইয়া"]),
        ("apu", &["আপু"]),
        ("dada", &["দাদা"]),
        ("didi", &["দিদি"]),
        ("mama", &["মামা"]),
        ("kaka", &["কাকা"]),
        ("chacha", &["চাচা"]),
        ("dost", &["দোস্ত"]),
        ("bondhu", &["বন্ধু"]),
        ("bondhura", &["বন্ধুরা"]),
        ("bondhuder", &["বন্ধুদের"]),
        ("shotti", &["সত্যি"]),
        ("shobthike", &["সবথেকে"]),
        ("shobcheye", &["সবচেয়ে", "সবচেয়ে"]),
        ("karon", &["কারণ"]),
        ("kintu", &["কিন্তু"]),
        ("tobu", &["তবু"]),
        ("tobuo", &["তবুও"]),
        ("othoba", &["অথবা"]),
        ("ebong", &["এবং"]),
        ("ar", &["আর"]),
        ("tai", &["তাই"]),
        ("tahole", &["তাহলে"]),
        ("tobe", &["তবে"]),
        ("hoyto", &["হয়তো", "হয়তো"]),
        ("bodhoy", &["বোধহয়", "বোধহয়"]),
        ("ontoto", &["অন্তত"]),
        ("protyek", &["প্রত্যেক"]),
        ("majhe", &["মাঝে"]),
        ("majhemajhe", &["মাঝেমাঝে"]),
        ("ekhon", &["এখন"]),
        ("tokhon", &["তখন"]),
        ("jokhon", &["যখন"]),
        ("kokhon", &["কখন"]),
        ("ekhane", &["এখানে"]),
        ("shekhane", &["সেখানে"]),
        ("jekhane", &["যেখানে"]),
        ("kothay", &["কোথায়"]),
        ("kothao", &["কোথাও"]),
        ("shobkisu", &["সবকিছু"]),
        ("shobkichu", &["সবকিছু"]),
        ("kichu", &["কিছু"]),
        ("kichutei", &["কিছুতেই"]),
        ("ektu", &["একটু"]),
        ("onek", &["অনেক"]),
        ("shob", &["সব"]),
        ("shokol", &["সকল"]),
        ("shomosto", &["সমস্ত"]),
        ("thik", &["ঠিক"]),
        ("vul", &["ভুল"]),
        ("bhalo", &["ভালো"]),
        ("khub", &["খুব"]),
        ("beshi", &["বেশি"]),
        ("kom", &["কম"]),

        // 4. Case Inflections, Classifiers & Postpositions
        ("deshe", &["দেশে"]),
        ("desher", &["দেশের"]),
        ("deshta", &["দেশটা"]),
        ("deshti", &["দেশটি"]),
        ("desheo", &["দেশেও"]),
        ("deshei", &["দেশেই"]),
        ("dine", &["দিনে"]),
        ("diner", &["দিনের"]),
        ("dinta", &["দিনটা"]),
        ("dinti", &["দিনটি"]),
        ("raate", &["রাতে"]),
        ("raater", &["রাতের"]),
        ("dur", &["দূর"]),
        ("dUr", &["দূর"]),
        ("dure", &["দূরে"]),
        ("dUre", &["দূরে"]),
        ("durer", &["দূরের"]),
        ("dureo", &["দূরেও"]),
        ("durei", &["দূরেই"]),
        ("raatta", &["রাতটা"]),
        ("shokale", &["সকালে"]),
        ("shokaler", &["সকালের"]),
        ("dupure", &["দুপুরে"]),
        ("shondhay", &["সন্ধ্যায়", "সন্ধ্যায়"]),
        ("boita", &["বইটা"]),
        ("boiti", &["বইটি"]),
        ("boigulo", &["বইগুলো"]),
        ("boigulote", &["বইগুলোতে"]),
        ("boigulor", &["বইগুলোর"]),
        ("garita", &["গাড়িটা"]),
        ("gariti", &["গাড়িটি"]),
        ("garite", &["গাড়িতে"]),
        ("garir", &["গাড়ির"]),
        ("barite", &["বাড়িতে"]),
        ("barir", &["বাড়ির"]),
        ("barita", &["বাড়িটা"]),
        ("bariti", &["বাড়িটি"]),
        ("ghore", &["ঘরে"]),
        ("ghorer", &["ঘরের"]),
        ("ghorta", &["ঘরটা"]),
        ("shohore", &["শহরে"]),
        ("shohorer", &["শহরের"]),
        ("grame", &["গ্রামে"]),
        ("gramer", &["গ্রামের"]),
        ("nodite", &["নদীতে"]),
        ("nodir", &["নদীর"]),
        ("mathe", &["মাঠে"]),
        ("mather", &["মাঠের"]),
        ("rasta", &["রাস্তা"]),
        ("rastay", &["রাস্তায়", "রাস্তায়"]),
        ("rastar", &["রাস্তার"]),
        ("haate", &["হাতে"]),
        ("haater", &["হাতের"]),
        ("paye", &["পায়ে", "পায়ে"]),
        ("mukhe", &["মুখে"]),
        ("chokhe", &["চোখে"]),
        ("chokher", &["চোখের"]),
        ("mathay", &["মাথায়", "মাথায়"]),
        ("moner", &["মনের"]),
        ("mone", &["মনে"]),
        ("bhabe", &["ভাবে"]),
        ("chobita", &["ছবিটা"]),
        ("chobiti", &["ছবিটি"]),
        ("chobigulo", &["ছবিগুলো"]),
        ("somoymoto", &["সময়মতো", "সময়মতো"]),

        // 5. Complex Sanskrit Conjuncts & Orthography
        ("ahban", &["আহ্বান"]),
        ("jihba", &["জিহ্বা"]),
        ("chinho", &["চিহ্ন"]),
        ("apranho", &["অপরাহ্ন"]),
        ("madhyanho", &["মধ্যাহ্ন"]),
        ("shayanho", &["সায়াহ্ন", "সায়াহ্ন"]),
        ("hritpindo", &["হৃৎপিণ্ড"]),
        ("bhabishshot", &["ভবিষ্যৎ"]),
        ("bhabisshot", &["ভবিষ্যৎ"]),
        ("sristi", &["সৃষ্টি"]),
        ("shristi", &["সৃষ্টি"]),
        ("srosta", &["স্রষ্টা"]),
        ("shrosta", &["স্রষ্টা"]),
        ("totto", &["তত্ত্ব"]),
        ("shatto", &["স্বত্ব"]),
        ("daridro", &["দারিদ্র্য"]),
        ("mahityo", &["মাহাত্ম্য"]),
        ("ucchash", &["উচ্ছ্বাস"]),
        ("ucchshinkhol", &["উচ্ছৃঙ্খল"]),
        ("protiddhoni", &["প্রতিধ্বনি"]),
        ("oshtomashchorjo", &["অষ্টমাশ্চর্য"]),
        ("durjogpurno", &["দুর্যোগপূর্ণ"]),
        ("shottadhikari", &["স্বত্বাধিকারী"]),
        ("shadhincheta", &["স্বাধীনচেতা"]),
        ("shikkha", &["শিক্ষা"]),
        ("shikkhok", &["শিক্ষক"]),
        ("porikkha", &["পরীক্ষা"]),
        ("porikkhay", &["পরীক্ষায়", "পরীক্ষায়"]),
        ("rokkha", &["রক্ষা"]),
        ("khoma", &["ক্ষমা"]),
        ("khoti", &["ক্ষতি"]),
        ("lokkhi", &["লক্ষ্মী"]),
        ("lokhyo", &["লক্ষ্য"]),
        ("shukkho", &["সূক্ষ্ম"]),
        ("tikkhno", &["তীক্ষ্ণ"]),
        ("bakkho", &["বাক্য"]),
        ("ottonto", &["অত্যন্ত"]),
        ("biddut", &["বিদ্যুৎ"]),
        ("biddan", &["বিদ্বান"]),
        ("shondha", &["সন্ধ্যা"]),
        ("shorbochcho", &["সর্বোচ্চ"]),
        ("porjaye", &["পর্যায়ে", "পর্যায়ে"]),
        ("shuryo", &["সূর্য"]),
        ("dhurjo", &["ধৈর্য"]),
        ("porboto", &["পর্বত"]),
        ("shorkar", &["সরকার"]),
        ("shorkari", &["সরকারি"]),
        ("shongbidhan", &["সংবিধান"]),
        ("shongshod", &["সংসদ"]),
        ("shongskriti", &["সংস্কৃতি"]),
        ("shongstha", &["সংস্থা"]),
        ("porishkar", &["পরিষ্কার"]),
        ("puroshkar", &["পুরস্কার"]),
        ("abishkar", &["আবিষ্কার"]),
        ("nomoshkar", &["নমস্কার"]),
        ("shondheho", &["সন্দেহ"]),
        ("shomossya", &["সমস্যা"]),
        ("utkrishto", &["উৎকৃষ্ট"]),
        ("drishtibhongi", &["দৃষ্টিভঙ্গি"]),
        ("srishtishil", &["সৃষ্টিশীল"]),
        ("shroddha", &["শ্রদ্ধা"]),
        ("upalobdhi", &["উপলব্ধি"]),
        ("antorikota", &["আন্তরিকতা"]),
        ("somorthon", &["সমর্থন"]),
        ("chhatrochhatriderkeo", &["ছাত্রছাত্রীদেরকেও"]),
        ("shomajkormidero", &["সমাজকর্মীদেরও"]),
        ("chikitshokderke", &["চিকিৎসকদেরকে"]),
        ("onishchitotay", &["অনিশ্চয়তায়", "অনিশ্চয়তায়"]),

        // 6. Ordinals, Fractions & Time
        ("dhai", &["আড়াই", "আড়াই"]),
        ("shoa", &["সোয়া", "সোয়া"]),
        ("shadhe", &["সাড়ে"]),
        ("pohela", &["পহেলা"]),
        ("doshra", &["দোসরা"]),
        ("tesra", &["তেসরা"]),
        ("choutha", &["চৌঠা"]),
        ("ekushe", &["একুশে"]),
        ("trayodash", &["ত্রয়োদশ", "ত্রয়োদশ"]),
        ("ditiyo", &["দ্বিতীয়", "দ্বিতীয়"]),
        ("tritiyo", &["তৃতীয়", "তৃতীয়"]),

        // 7. Bilingual / Digital Loanwords & Inflected Forms
        ("computer", &["কম্পিউটার"]),
        ("computere", &["কম্পিউটারে"]),
        ("computerer", &["কম্পিউটারের"]),
        ("computerta", &["কম্পিউটারটা"]),
        ("computerti", &["কম্পিউটারটি"]),
        ("computergulo", &["কম্পিউটারগুলো"]),
        ("laptop", &["ল্যাপটপ"]),
        ("laptoper", &["ল্যাপটপের"]),
        ("laptopta", &["ল্যাপটপটা"]),
        ("laptopte", &["ল্যাপটপে"]),
        ("phone", &["ফোন"]),
        ("phoner", &["ফোনের"]),
        ("phoneta", &["ফোনটা"]),
        ("phonete", &["ফোনে"]),
        ("mobile", &["মোবাইল"]),
        ("mobiler", &["মোবাইলের"]),
        ("mobileta", &["মোবাইলটা"]),
        ("mobilete", &["মোবাইলে"]),
        ("smartphone", &["স্মার্টফোন"]),
        ("smartphonete", &["স্মার্টফোনে"]),
        ("password", &["পাসওয়ার্ড", "পাসওয়ার্ড"]),
        ("passwordti", &["পাসওয়ার্ডটি", "পাসওয়ার্ডটি"]),
        ("passwordta", &["পাসওয়ার্ডটা", "পাসওয়ার্ডটা"]),
        ("file", &["ফাইল"]),
        ("fileti", &["ফাইলটি"]),
        ("fileta", &["ফাইলটা"]),
        ("filegulo", &["ফাইলগুলো"]),
        ("account", &["অ্যাকাউন্ট"]),
        ("accountti", &["অ্যাকাউন্টটি"]),
        ("accountta", &["অ্যাকাউন্টটা"]),
        ("application", &["অ্যাপ্লিকেশন"]),
        ("applicationta", &["অ্যাপ্লিকেশনটা"]),
        ("applicationti", &["অ্যাপ্লিকেশনটি"]),
        ("software", &["সফটওয়্যার", "সফটওয়্যার"]),
        ("softwaree", &["সফটওয়্যারে", "সফটওয়্যারে"]),
        ("softwareta", &["সফটওয়্যারটা", "সফটওয়্যারটা"]),
        ("update", &["আপডেট"]),
        ("updatee", &["আপডেটেই", "আপডেটে"]),
        ("updateta", &["আপডেটটা"]),
        ("developer", &["ডেভেলপার"]),
        ("developerra", &["ডেভেলপাররা"]),
        ("developerder", &["ডেভেলপারদের"]),
        ("screenshot", &["স্ক্রিনশট"]),
        ("screenshotta", &["স্ক্রিনশটটা"]),
        ("notification", &["নোটিফিকেশন"]),
        ("notificationgulo", &["নোটিফিকেশনগুলো"]),
        ("internet", &["ইন্টারনেট"]),
        ("interneter", &["ইন্টারনেটের"]),
        ("internette", &["ইন্টারনেটে"]),
        ("browser", &["ব্রাউজার"]),
        ("browser-e", &["ব্রাউজারে"]),
        ("browserer", &["ব্রাউজারের"]),
        ("server", &["সার্ভার"]),
        ("serverer", &["সার্ভারের"]),
        ("servere", &["সার্ভারে"]),
        ("office", &["অফিস"]),
        ("officee", &["অফিসে"]),
        ("officer", &["অফিসের"]),
        ("doctor", &["ডাক্তার"]),
        ("doctorer", &["ডাক্তারের"]),
        ("doctorke", &["ডাক্তারকে"]),
        ("hospital", &["হাসপাতাল", "হসপিটাল"]),
        ("meeting", &["মিটিং"]),
        ("meetinge", &["মিটিংয়ে", "মিটিংয়ে", "মিটিংএ"]),
        ("meetingta", &["মিটিংটা"]),
        ("message", &["মেসেজ"]),
        ("messageta", &["মেসেজটা"]),
        ("messagete", &["মেসেজে"]),
        ("post", &["পোস্ট"]),
        ("postta", &["পোস্টটা"]),
        ("poste", &["পোস্টে"]),
        ("share", &["শেয়ার", "শেয়ার"]),
        ("comment", &["কমেন্ট"]),
        ("commentta", &["কমেন্টটা"]),
        ("commentgulo", &["কমেন্টগুলো"]),
    ];

    let mut passed = 0;
    let mut failures = Vec::new();

    for &(input, expected_list) in test_cases {
        let (cands, _) = sugg.suggest(input, true, true, &empty_memory);
        if cands.is_empty() {
            failures.push((input, expected_list[0], "No candidates returned".to_string()));
        } else if expected_list.contains(&cands[0].as_str()) {
            passed += 1;
        } else {
            failures.push((input, expected_list[0], cands[0].clone()));
        }
    }

    println!("\n=======================================================");
    println!("Simulation Results: {} / {} Passed ({:.1}%)", 
        passed, test_cases.len(), (passed as f64 / test_cases.len() as f64) * 100.0);
    println!("=======================================================");

    let report = format!("Simulation Results: {} / {} Passed ({:.1}%)\n\nFailures: {}\n", passed, test_cases.len(), (passed as f64 / test_cases.len() as f64) * 100.0, failures.len());
    let mut full_report = report;
    for (inp, exp, got) in &failures {
        full_report.push_str(&format!("{:<25} -> Expected: {:<20} | Got: {}\n", inp, exp, got));
    }
    let _ = std::fs::write("/home/smsiam/.gemini/antigravity-ide/brain/2eaa4b67-9056-4772-bda1-cb090af46c39/scratch/simulation_failures.txt", full_report);

    assert!(failures.is_empty(), "Failed {} out of {} test cases in deep simulation", failures.len(), test_cases.len());
}
